version: "3.7"

services:
    runner:
      image: flynow/github_runner
      build:
        context: docker
      environment:
        RUNNER_NAME: ${RUNNER_NAME}
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        #RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
        #GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        RUNNER_TOKEN: ${RUNNER_TOKEN}
        RUNNER_LABELS: ${RUNNER_LABELS}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker:/var/lib/docker
        - ./work:/home/runner/_work
